version: '3.1'
services:
  nginx:
    image: nginx:alpine
    container_name: prod_proxy
    ports:
      - "0.0.0.0:80:80"
    #  - "443:443"
    volumes:
      - ./bin/data/nginx:/etc/nginx/conf.d
    #  - ./bin/certbot/conf:/etc/letsencrypt
    #  - ./bin/certbot/www:/var/www/certbot
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  #certbot:
  #  image: certbot/certbot
  #  container_name: prod_certbot
  #  volumes:
  #    - ./bin/certbot/conf:/etc/letsencrypt
  #    - ./bin/certbot/www:/var/www/certbot
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  odoo:
    build: 
      context: ./bin
      args:
        ODOO_VERSION: "13.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: prod_odoo
    restart: always
    depends_on:
      - prod_db
    ports:
      - "8069"
      - "8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./bin/config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=prod_db
      - USER=odoo
      - PASSWORD=myodoo

  odoodb:
    image: postgres:13
    container_name: prod_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgweb:
    image: sosedoff/pgweb
    container_name: prod_pgweb
    restart: always
    depends_on:
      - prod_db
    ports:
      - "13081:8081"
    environment:
      DATABASE_URL: postgres://odoo:myodoo@prod_db:5432/postgres?sslmode=disable

volumes:
  odoo-web-data:
  odoo-db-data:
